Rails/AssertNot:
  Include:
    - '**/test/**/*'

Rails/RefuteMethods:
  Include:
    - '**/test/**/*'

Rails/IndexBy:
  Enabled: true

Rails/IndexWith:
  Enabled: true

Style/AndOr:
  Enabled: true

Layout/ClosingHeredocIndentation:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Layout/EndOfLine:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: only_before

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: either

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods
  Exclude:
    - '**/*.md'

Layout/IndentationWidth:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - 'actionview/test/**/*.builder'
    - 'actionview/test/**/*.ruby'
    - 'actionpack/test/**/*.builder'
    - 'actionpack/test/**/*.ruby'
    - 'activestorage/db/migrate/**/*.rb'
    - 'activestorage/db/update_migrate/**/*.rb'
    - 'actionmailbox/db/migrate/**/*.rb'
    - 'actiontext/db/migrate/**/*.rb'
    - '**/*.md'

Style/MapToHash:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/IndentationStyle:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/RedundantPercentQ:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/Debugger:
  Enabled: true
  DebuggerRequires:
    - debug

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateMagicComment:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/ErbNewArguments:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/MissingCopEnableDirective:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/RedundantCopEnableDirective:
  Enabled: true

Lint/RedundantRequireStatement:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/UriEscapeUnescape:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/InterpolationCheck:
  Enabled: true
  Exclude:
    - '**/test/**/*'

Lint/SafeNavigationChain:
  Enabled: true

Style/EvalWithLocation:
  Enabled: true
  Exclude:
    - '**/test/**/*'

Style/ParenthesesAroundCondition:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

Style/ColonMethodCall:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/RedundantCondition:
  Enabled: true

Style/RedundantDoubleSplatHashBraces:
  Enabled: true

Style/OpenStructUse:
  Enabled: true

Style/ArrayIntersect:
  Enabled: true

Style/KeywordArgumentsMerging:
  Enabled: true
