#!/usr/bin/env ruby

require 'net/http'
require 'uri'
require 'nokogiri'
require 'fileutils'

# Carpeta donde se guardarán las imágenes
DOWNLOAD_PATH = './data'
# Solo .img o .png
VALID_EXTENSIONS = %w[.img .jpg .png .gif .bmp]

# Obtener URL desde argumento
url = ARGV[-1] || 'https://www.w3schools.com'
uri = URI(url)

# Fetch HTML
html = Net::HTTP.get(uri)

# Parse HTML
doc = Nokogiri::HTML(html)

# Extraer URLs de imágenes y normalizarlas
images = doc.css('img').map do |img|
  src = img['src']
  URI.join(url, src).to_s if src
end.compact

puts "Found #{images.size} images:"
images.each { |img| puts img }

# Crear carpeta si no existe
FileUtils.mkdir_p(DOWNLOAD_PATH)

# Descargar cada imagen válida
images.each do |img_url|
  begin
    img_uri = URI(img_url)
    filename = File.basename(img_uri.path)
    ext = File.extname(filename).downcase

    # Solo .img o .png
    next unless VALID_EXTENSIONS.include?(ext)
    filepath = File.join(DOWNLOAD_PATH, filename)

    # Descargar
    Net::HTTP.start(img_uri.host, img_uri.port, use_ssl: img_uri.scheme == 'https') do |http|
      response = http.get(img_uri.path)
      File.open(filepath, 'wb') { |file| file.write(response.body) }
    end

    puts "Downloaded: #{filepath}"
  rescue => e
    puts "Failed to download #{img_url}: #{e.message}"
  end
end
